// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-posts.ts
var search_posts_default = defineTool({
  name: "search_posts",
  title: "Search neighborhood posts",
  description: "Search Naighborly posts (offers and requests) by text, category, intent, neighborhood, urgency or resolved state.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match in the title or description."),
    category: z.enum(["Item", "Service", "Swap"]).optional(),
    intent: z.enum(["Offer", "Request"]).optional(),
    neighborhood: z.string().trim().optional().describe("Partial location/neighborhood name."),
    urgent_only: z.boolean().optional(),
    include_resolved: z.boolean().optional().describe("Defaults to false."),
    limit: z.number().int().min(1).max(50).optional().describe("Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("posts").select("id,title,description,category,intent,location,urgent,resolved,created_at,image_url").order("created_at", { ascending: false }).limit(input.limit ?? 20);
    if (input.query) q = q.or(`title.ilike.%${input.query}%,description.ilike.%${input.query}%`);
    if (input.category) q = q.eq("category", input.category);
    if (input.intent) q = q.eq("intent", input.intent);
    if (input.neighborhood) q = q.ilike("location", `%${input.neighborhood}%`);
    if (input.urgent_only) q = q.eq("urgent", true);
    if (!input.include_resolved) q = q.eq("resolved", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_post_default = defineTool2({
  name: "get_post",
  title: "Get a post",
  description: "Fetch a single Naighborly post by id, with its owner's public profile details.",
  inputSchema: { post_id: z2.string().uuid().describe("The post id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ post_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: post, error } = await supabase.from("posts").select("*").eq("id", post_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!post) return { content: [{ type: "text", text: "Post not found" }], isError: true };
    const { data: owner } = await supabase.from("profiles").select("id,display_name,neighborhood,bio,trust_tier,asanti_received,avatar_url").eq("id", post.owner_id).maybeSingle();
    return {
      content: [{ type: "text", text: JSON.stringify({ post, owner }) }],
      structuredContent: { post, owner: owner ?? null }
    };
  }
});

// src/lib/mcp/tools/create-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_post_default = defineTool3({
  name: "create_post",
  title: "Create a post",
  description: "Create a new Naighborly post (an offer or a request) on behalf of the signed-in neighbor.",
  inputSchema: {
    title: z3.string().trim().min(3).max(120),
    description: z3.string().trim().min(3).max(2e3),
    category: z3.enum(["Item", "Service", "Swap"]),
    intent: z3.enum(["Offer", "Request"]),
    location: z3.string().trim().min(1).max(120).optional().describe("Neighborhood label. Defaults to the user's saved neighborhood."),
    urgent: z3.boolean().optional(),
    note: z3.string().trim().max(500).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    let location = input.location;
    let latitude = null;
    let longitude = null;
    const { data: profile } = await supabase.from("profiles").select("neighborhood,latitude,longitude").eq("id", userId).maybeSingle();
    if (!location) location = profile?.neighborhood ?? "Nairobi";
    if (profile && location === profile.neighborhood) {
      latitude = profile.latitude ?? null;
      longitude = profile.longitude ?? null;
    }
    const { data, error } = await supabase.from("posts").insert({
      owner_id: userId,
      title: input.title,
      description: input.description,
      category: input.category,
      intent: input.intent,
      location,
      latitude,
      longitude,
      urgent: input.urgent ?? false,
      note: input.note ?? null
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/resolve-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var resolve_post_default = defineTool4({
  name: "resolve_post",
  title: "Mark a post resolved",
  description: "Mark one of the signed-in neighbor's own posts as resolved (or reopen it by setting resolved to false).",
  inputSchema: {
    post_id: z4.string().uuid(),
    resolved: z4.boolean().optional().describe("Defaults to true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ post_id, resolved }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("posts").update({ resolved: resolved ?? true }).eq("id", post_id).eq("owner_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No post updated \u2014 it does not exist or you do not own it." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var my_profile_default = defineTool5({
  name: "my_profile",
  title: "My neighbor profile",
  description: "Get the signed-in neighbor's Naighborly profile: name, neighborhood, trust tier, asanti received, and their own posts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error } = await supabase.from("profiles").select("id,display_name,neighborhood,bio,trust_tier,asanti_received,avatar_url,created_at").eq("id", userId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: posts } = await supabase.from("posts").select("id,title,category,intent,resolved,urgent,created_at").eq("owner_id", userId).order("created_at", { ascending: false }).limit(25);
    return {
      content: [{ type: "text", text: JSON.stringify({ profile, posts: posts ?? [] }) }],
      structuredContent: { profile: profile ?? null, posts: posts ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "okheiiyncxulfkozgndt";
var mcp_default = defineMcp({
  name: "nairobi-neighborly-hub",
  title: "Nairobi Neighborly Hub",
  version: "0.1.0",
  instructions: "Tools for Naighborly, a Nairobi neighborhood help-and-share app. Use `search_posts` to find neighbor offers and requests, `get_post` for full detail plus the owner's trust standing, `create_post` to post on the signed-in neighbor's behalf, `resolve_post` to close their own post, and `my_profile` for their standing and posts. All tools act as the signed-in neighbor.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_posts_default, get_post_default, create_post_default, resolve_post_default, my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
